version: '3.7'

x-common-variables: &common-variables
  MYSQL_DATABASE: books
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mysql_db:
    container_name: nginx_docker_exp_mysql_db
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - './setup.sql:/docker-entrypoint-initdb.d/setup.sql'
    ports:
      - 9906:3306
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost

  nginx:
    container_name: nginx_docker_exp_nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3050:80

  api:
    container_name: nginx_docker_exp_api
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - mysql_db
    volumes:
      - ./server:/var/www/api
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db

  client:
    container_name: nginx_docker_exp_client
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/var/www/client

  adminer:
    container_name: nginx_docker_exp_adminer
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
